### ISSUE TITLE
Error: invalid character '<' looking for beginning of value <!DOCTYPE html>

### ISSUE THREAD

**Issue by imsamroy** [aandrew-me/tgpt#5] opened 2023-04-23 05:58 UTC
I just installed using curl on my Arch Linux machine and whenever I try to give it a prompt, it just shows this error... I even tried reinstalling but nothing works as of now.
![image](https://user-images.githubusercontent.com/92716271/233822333-552d8df5-7d69-40a4-869e-88c993e4bb5a.png)

**Comment by aandrew-me** [comment] 2023-04-23 06:02
Yes this happens when the server is not accepting your request. I am trying to figure it out why it only happens for some users.

**Comment by aandrew-me** [comment] 2023-04-23 06:05
Can you try if this problem persists with a proxy or vpn?

**Comment by kaleab27** [comment] 2023-04-23 07:28
> Can you try if this problem persists with a proxy or vpn?

I also encountered the same problem but, my issue was resolved subsequent to disconnecting my VPN.

**Comment by aandrew-me** [comment] 2023-04-24 06:34
I am closing this as its a duplicate of #2

**Closed by aandrew-me** 2023-04-24 06:34 UTC
